<?php
$servicePages = [
    'meters-as-a-service' => [
        'title' => 'Meters as a Service',
        'eyebrow' => 'Service',
        'summary' => 'Supply, install and manage smart prepaid water meters for billing, revenue collection and water-loss control.',
        'hero' => 'assets/img/meter01.png',
        'url' => 'service-meters-as-a-service.php',
        'intro' => 'Leeroy Systems manages the full meter lifecycle — from site readiness and installation through to ongoing maintenance and reporting. With in-house CIU assembly and repair that cuts replacement costs by up to 60%, 24/7 support via a Network Operations Centre, and an accredited calibration lab (in partnership with iCurrate Laboratories) covering ultrasonic, multijet and mechanical meters from DN50 to DN200, this is a genuinely end-to-end managed service.',
        'points' => [
            'Domestic, bulk and ultrasonic smart prepaid meter supply, assembly and installation.',
            'In-house CIU assembly and repair — reducing replacement costs by up to 60%.',
            '24/7 maintenance and field support via a dedicated Network Operations Centre.',
            'Accredited meter calibration lab (iCurrate Laboratories) for DN50–DN200 meter types.',
            'Usage reporting for billing, revenue protection and water loss management.',
        ],
        'outcome' => 'A dependable metering environment that improves transparency, prepaid control and day-to-day water management — all maintained and supported in-house.',
    ],
    'data-as-a-service' => [
        'title' => 'Data as a Service',
        'eyebrow' => 'Service',
        'summary' => 'Live dashboards, anomaly detection and automated alerts that turn meter readings into actionable operational intelligence.',
        'hero' => 'assets/img/star.png',
        'url' => 'service-data-as-a-service.php',
        'intro' => 'This service turns raw meter readings and field activity into usable operational intelligence. Live dashboards with heatmaps, anomaly detection and zone-level reporting keep decision-makers informed in real time — with data synced every 15 minutes. The platform also detects billing discrepancies, tracks payment and credit status, and dispatches automated alerts for tamper events, dry pipes, burst mains and low credit via SMS, email or API.',
        'points' => [
            'Live dashboards with heatmaps, anomaly detection and zone-level reporting.',
            'Data synced every 15 minutes for near real-time operational visibility.',
            'Automated alerts for tamper, dry pipe, burst mains and low credit — via SMS, email or API.',
            'Billing discrepancy detection and payment and credit tracking.',
            'Centralised storage for meter, customer and usage records with data quality checks.',
        ],
        'outcome' => 'Cleaner, faster information flow between field operations, billing teams and management — with automated alerts so nothing goes unnoticed.',
    ],
    'network-as-a-service' => [
        'title' => 'Network as a Service',
        'eyebrow' => 'Service',
        'summary' => 'End-to-end IoT network infrastructure — LoRaWAN, Sigfox and NB-IoT — owned, sited and maintained in-house across Botswana.',
        'hero' => 'assets/img/tower.png',
        'url' => 'service-network-as-a-service.php',
        'intro' => 'Smart metering depends on dependable communication. Leeroy Systems owns and manages its end-to-end IoT network infrastructure, combining three complementary technologies: LoRaWAN (up to 15km range with 10+ year battery life), Sigfox (ultra-narrowband requiring no additional infrastructure overhead), and NB-IoT (licensed LTE with SLA-backed reliability). All sites are designed, deployed and maintained in-house across Botswana.',
        'points' => [
            'LoRaWAN network — up to 15km range, 10+ year device battery life.',
            'Sigfox — ultra-narrowband connectivity with no infrastructure overhead.',
            'NB-IoT — licensed LTE network with SLA-backed service continuity.',
            'All infrastructure sited, deployed and maintained in-house across Botswana.',
            'Network coverage monitoring for branches, field zones and connected metering assets.',
        ],
        'outcome' => 'A purpose-built, fully managed IoT network that keeps every meter connected — owned and operated entirely by Leeroy Systems.',
    ],
    'software-as-a-service' => [
        'title' => 'Software as a Service',
        'eyebrow' => 'Service',
        'summary' => 'A cloud-hosted multi-utility vending platform built in-house in Gaborone — accessible via mobile, kiosk or agent.',
        'hero' => 'assets/img/softass.png',
        'url' => 'service-software-as-a-service.php',
        'intro' => 'Beyond installation, clients need digital tools that support billing, vending and day-to-day operations. Leeroy Systems delivers a cloud-hosted multi-utility vending platform covering water, electricity, gas and time — accessible via mobile, kiosk or agent network. The platform is white-labelled, API-integrated and STS-compliant for electricity token vending, and is built and maintained entirely by an in-house development team in Gaborone.',
        'points' => [
            'Cloud-hosted multi-utility vending platform (water, electricity, gas, time).',
            'Accessible via mobile app, kiosk or agent — wherever customers are.',
            'White-labelled and API-integrated for seamless client branding and system connection.',
            'STS-compliant electricity token vending built in.',
            'Built and maintained entirely by an in-house development team in Gaborone.',
        ],
        'outcome' => 'A fully owned, locally built digital platform that improves adoption, simplifies vending and connects every part of the metering operation.',
    ],
];

$projectPages = [
    'city-of-francistown-council' => [
        'title' => 'City of Francistown Council',
        'eyebrow' => 'Project case',
        'summary' => '13-month contract for installation of domestic and bulk smart prepaid water meters.',
        'hero' => 'assets/img/ft_pumper.jpeg',
        'url' => 'project-city-of-francistown-council.php',
        'intro' => 'The Francistown deployment focused on practical smart prepaid metering for municipal water control. The work combined field installation, commissioning, customer support and reporting discipline over a defined contract period.',
        'points' => [
            'Domestic and bulk smart prepaid meter installation.',
            'Field coordination for council water management zones.',
            'Commissioning support and meter-readiness checks.',
            'Operational reporting for adoption and revenue visibility.',
        ],
        'outcome' => 'The project strengthened prepaid water management capability and gave the council clearer usage and installation visibility.',
        'images' => ['assets/img/ft_car.jpeg', 'assets/img/ft2.jpg', 'assets/img/ft1.jpg'],
    ],

    'palapye-district-council' => [
    'title' => 'Palapye District Council',
    'eyebrow' => 'Project case',
    'summary' => 'Pilot project for domestic and bulk smart prepaid water metering.',
    'hero' => 'assets/img/diphalane_mall.jpg',
    'url' => 'project-palapye-district-council.php',
    'intro' => 'The Palapye pilot gave the client a controlled way to test smart prepaid metering in real operating conditions. The work helped validate field processes, technical reliability and customer readiness.',
    'points' => [
        'Pilot deployment for domestic and bulk metering use cases.',
        'Field feedback collection during early adoption.',
        'Support for metering performance and network visibility.',
        'Readiness insight for wider rollout planning.',
    ],
    'outcome' => 'The pilot created a practical evidence base for future smart metering expansion.',
    'images' => ['assets/img/palapye.png', 'assets/img/diphalane_mall.jpg', 'assets/img/thumbnail.jpg'],
],
   
    'debswana-jwaneng' => [
        'title' => 'Debswana Jwaneng',
        'eyebrow' => 'Project case',
        'summary' => 'Smart prepaid water meter installation and monitoring support.',
        'hero' => 'assets/img/jw3.jpeg',
        'url' => 'project-debswana-jwaneng.php',
        'intro' => 'The Debswana Jwaneng work supported a high-value operational environment where reliable water monitoring matters. The engagement centred on smart meter installation, dependable readings and ongoing support.',
        'points' => [
            'Smart prepaid water meter installation for operational sites.',
            'Monitoring support for usage and meter status.',
            'Technical assistance for dependable field performance.',
            'Reporting support for operational accountability.',
        ],
        'outcome' => 'The client gained stronger monitoring support and more accountable water usage information.',
        'images' => ['assets/img/jwa1.jpg', 'assets/img/jwa2.jpg', 'assets/img/car.jpg'],
    ],
    'water-utilities-corporation-phase-1' => [
        'title' => 'Water Utilities Corporation Phase 1',
        'eyebrow' => 'Project case',
        'summary' => 'Installation of domestic and bulk smart prepaid water meters.',
        'hero' => 'assets/img/wuc-3.jpg',
        'url' => 'project-water-utilities-corporation-phase-1.php',
        'intro' => 'This phase supported Water Utilities Corporation with smart prepaid metering infrastructure for domestic and bulk environments. The project focused on installation quality, field coordination and practical water control.',
        'points' => [
            'Domestic and bulk smart prepaid water meter installation.',
            'Field support for deployment planning and execution.',
            'Meter setup and commissioning assistance.',
            'Usage visibility for billing and water management teams.',
        ],
        'outcome' => 'The phase improved smart metering coverage and supported more transparent prepaid water operations.',
        'images' => ['assets/img/wuc5.jpg', 'assets/img/wuc-2.jpg', 'assets/img/wuc-1.jpg'],
    ],
];
